#pragma once

#define STARTUP_SONG SONG(PLANCK_SOUND)

#define MOUSEKEY_WHEEL_MAX_SPEED 1

#define TAPPING_TERM 200

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD
#define RETRO_TAPPING

#define COMBO_COUNT 1

#define ENCODER_RESOLUTION 4
#define ENCODER_DEFAULT_POS 0x3
